from typing import Protocol

from app.domain.entities.recipe import Recipe


class RecipeRepository(Protocol):
    async def create(self, recipe: Recipe) -> Recipe: ...
    async def get_by_id(self, recipe_id: str) -> Recipe | None: ...
    async def get_by_code(self, code: str) -> Recipe | None: ...
    async def list_all(self, *, skip: int = 0, limit: int = 100) -> list[Recipe]: ...
    async def update_by_code(self, code: str, recipe: Recipe) -> Recipe | None: ...
    async def delete_by_code(self, code: str) -> bool: ...
