from typing import Protocol

from app.domain.entities.sku_list import SkuList


class SkuListRepository(Protocol):
    async def create(self, entity: SkuList) -> SkuList: ...
    async def list_all(self, *, limit: int = 100) -> list[SkuList]: ...
    async def get_by_id(self, sku_list_id: str) -> SkuList | None: ...
    async def get_for_simulation(self) -> SkuList | None: ...
    async def update(self, sku_list_id: str, entity: SkuList) -> SkuList | None: ...
    async def delete(self, sku_list_id: str) -> bool: ...
